[project]
name = "mcp-evals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "voorhs", email = "ilya_alekseev_2016@list.ru" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["uv_build>=0.8.8,<0.9.0"]
build-backend = "uv_build"
