name: CI

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v3
        with:
          version: "0.14.14" # same as in pyproject.toml

  type-check:
    uses: ./.github/workflows/reusable.yaml
    with:
      test_command: "mypy ."

  test:
    uses: ./.github/workflows/reusable.yaml
    with:
      test_command: "pytest"
