name: CI

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: "Install ruff"
        uses: astral-sh/ruff-action@v4.0.0
        with:
          version: "0.14.14" # same as in pyproject.toml
          args: "--version"
      - name: "Check if formatted"
        run: "ruff format --check"
      - name: "Check codestyle"
        run: "ruff check"

  type-check:
    uses: ./.github/workflows/reusable.yaml
    with:
      test_command: "mypy ."

  test:
    uses: ./.github/workflows/reusable.yaml
    with:
      test_command: "pytest"
